#!/bin/bash

commit_msg=$(cat $1)

if [[ ! $commit_msg =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test) ]]; then
    echo "Commit message must start with 'build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test'"
    exit 1
fi
