name: PR Reminder

on:
  pull_request:
    types: [opened, reopened]
    
  workflow_dispatch:


jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install dayjs

    - name: Send reminder message
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      run: |
        const fetch = require('node-fetch');
        const dayjs = require('dayjs');
        const utc = require('dayjs/plugin/utc');
        const timezone = require('dayjs/plugin/timezone');
        dayjs.extend(utc);
        dayjs.extend(timezone);

        const createdAt = process.env.GITHUB_EVENT_PULL_REQUEST_CREATED_AT;
        const prUrl = process.env.GITHUB_EVENT_PULL_REQUEST_HTML_URL;
        const prTitle = process.env.GITHUB_EVENT_PULL_REQUEST_TITLE;
        const slackWebhookUrl = process.env.SLACK_WEBHOOK_URL;

        const now = dayjs.utc().tz('America/New_York');
        const created = dayjs.utc(createdAt).tz('America/New_York');
        const minutesOpen = now.diff(created, 'minute');

        if (minutesOpen >= 10) {
          const message = `Reminder: Pull request <${prUrl}|#${process.env.GITHUB_EVENT_NUMBER} ${prTitle}> has been open for ${minutesOpen} minutes.`;
          const data = {
            text: message
          };
          const options = {
            method: 'POST',
            headers: {
              'Content-type': 'application/json'
            },
            body: JSON.stringify(data)
          };
          fetch(slackWebhookUrl, options)
            .then(() => {
              console.log(`Sent reminder message: ${message}`);
            })
            .catch((error) => {
              console.error(error);
            });
        }
