name: PR Reminder

on:
  pull_request:
    types: [opened, reopened]
  
  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
    - name: Send reminder message
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      run: |
        created_at=${{ github.event.pull_request.created_at }}
        pr_url=${{ github.event.pull_request.html_url }}
        pr_title=${{ github.event.pull_request.title }}
        slack_webhook_url=${SLACK_WEBHOOK_URL}

        now=$(date +%s)
        created=$(date -d "${created_at}" +%s)
        minutes_open=$(( (now - created) / 60 ))

        if [[ ${minutes_open} -ge 10 ]]; then
          message="Reminder: Pull request <${pr_url}|#${GITHUB_EVENT_NUMBER} ${pr_title}> has been open for ${minutes_open} minutes."
          curl -X POST --data-urlencode "payload={\"channel\": \"#test\", \"username\": \"webhookbot\", \"text\": \"This is posted to #test and comes from a bot named webhookbot.\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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
          echo "Sent reminder message: ${message}"
        fi
