name: Pull Request Reminder Python

on:
  schedule:
    - cron: '0 9 * * 1-5' # Remind on weekdays at 9am
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Use Python 3
      - name: Install dependencies
        run: pip install requests
      - name: Check for stale pull requests
        run: |
          stale_prs=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls?state=open | jq '.[] | select((now - (.updated_at | fromdateiso8601 | tonumber)) > 600) | .html_url' | tr -d '"')
          if [ ! -z "$stale_prs" ]; then
            message="The following pull requests have been open for more than 10 minutes:"
            for pr in $stale_prs; do
              message="$message\n• $pr"
            done
            curl -X POST -H 'Content-type: application/json' --data "payload={\"text\":\"$message\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
          fi
