name: slack-notification

on:
  schedule:
    - cron: '0 9 * * 1-5' # Remind on weekdays at 9am
  workflow_dispatch:


jobs:
  slack-notifications:
    runs-on: ubuntu-20.04
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for stale pull requests
        id: GetMessage
        run: |
          stale_prs=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls?state=open | jq '.[] | select((now - (.updated_at | fromdateiso8601 | tonumber)) > 600) | "- " + .title + " " + .html_url' | tr -d '"')
          if [ ! -z "$stale_prs" ]; then
            message="The following pull requests have been open for more than 10 minutes:"
            for pr in $stale_prs; do
              message="$message\n• $pr"
            done
            echo "message=$message" >> "$GITHUB_OUTPUT"
          fi
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: test
          slack-text: "${{ steps.GetMessage.outputs.message }} @here"
